### ISSUE TITLE
Failing PlantUML test - testMathSVGGeneration

### ISSUE THREAD

**Issue by snecklifter** [asciidoctor/asciidoctor-diagram-java#5]
I'm also seeing the following test fail for PlantUML (all others are ok):

```java.lang.AssertionError: ParseError at [row,col]:[4,1]
Message: expected start or end tag
	at org.junit.Assert.fail(Assert.java:88)
	at org.asciidoctor.diagram.plantuml.Assert.assertIsSVG(Assert.java:39)
	at org.asciidoctor.diagram.plantuml.PlantUMLTest.testMathSVGGeneration(PlantUMLTest.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
...
```

**Comment by pepijnve** [comment]
Looks like this was an XML parsing issue in the quick and dirty output validation logic. I didn't bother figuring out what was wrong with the stax parser and used a dom one instead.
